
package ec.edu.espe.Spa.view;

import com.mongodb.client.MongoCollection;
import static com.mongodb.client.model.Filters.eq;
import ec.edu.espe.Spa.controller.MongoDBConnection;
import ec.edu.espe.Spa.controller.UserController;
import ec.edu.espe.Spa.model.User;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import org.bson.Document;

/**
 *
 * @author Steven Pozo, Erick Moreira, Elkin Pabón, Diego Ponce, DCCO-ESPE, DEES Developers
 */
public class Frm_InterfaceLogin extends javax.swing.JFrame {
UserController userController;
    /**
     * Creates new form intefaz_Inicial
     */
 //   private UserController userController;
    public Frm_InterfaceLogin() {
        initComponents();
        MongoDBConnection.connectDatabase();
        
        userController = new UserController("User");
        this.setTitle("Flor de piel");
        setIconImage(getIconImage());
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    public void login(){
        User user;
        user = new User(txt_username1.getText(),new String (passwordUser.getPassword()));
        
        Document doc = userController.read(userController.buildDocumentUser(user));
        
        if (doc !=null) {
            
            frmIS = new Frm_InterfaceSchedule();
            frmIS.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "USUARIO O CONTRASEÑA INVÁLIDO:\n"+"Ingrese nuevamente", "Acceso denegado",
            JOptionPane.ERROR_MESSAGE);
            txt_username1.setText("");
            passwordUser.setText("");
        }
    }
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Images/icono.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_help = new javax.swing.JButton();
        lbl_Lguito = new javax.swing.JLabel();
        lbl_SpaFondo2 = new javax.swing.JLabel();
        lbl_SpaFondo1 = new javax.swing.JLabel();
        lbl_SoloLogo1 = new javax.swing.JLabel();
        lbl_LeatherFlowerSystem = new javax.swing.JLabel();
        lbl_password = new javax.swing.JLabel();
        Separeitor_password = new javax.swing.JSeparator();
        lbl_username = new javax.swing.JLabel();
        txt_username1 = new javax.swing.JTextField();
        Separeitor_username1 = new javax.swing.JSeparator();
        passwordUser = new javax.swing.JPasswordField();
        btn_Login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1210, 620));
        jPanel1.setPreferredSize(new java.awt.Dimension(1210, 620));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_help.setBackground(new java.awt.Color(204, 152, 243));
        btn_help.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_help.setText("Ayuda");
        btn_help.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_helpActionPerformed(evt);
            }
        });
        jPanel1.add(btn_help, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        lbl_Lguito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FLOR DE PIEL BN1.jpg"))); // NOI18N
        jPanel1.add(lbl_Lguito, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, 400, 360));

        lbl_SpaFondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FONDO SPA.jpg"))); // NOI18N
        lbl_SpaFondo2.setText("jLabel1");
        jPanel1.add(lbl_SpaFondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 350, 620));

        lbl_SpaFondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FONDO SPA.jpg"))); // NOI18N
        lbl_SpaFondo1.setText("jLabel1");
        jPanel1.add(lbl_SpaFondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 350, 620));

        lbl_SoloLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LOGOFP.jpg"))); // NOI18N
        jPanel1.add(lbl_SoloLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        lbl_LeatherFlowerSystem.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        lbl_LeatherFlowerSystem.setForeground(new java.awt.Color(255, 255, 255));
        lbl_LeatherFlowerSystem.setText("Flor de Piel Spa");
        jPanel1.add(lbl_LeatherFlowerSystem, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 240, -1));

        lbl_password.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_password.setText("CONTRASEÑA:");
        jPanel1.add(lbl_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        Separeitor_password.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(Separeitor_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 407, 340, -1));

        lbl_username.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_username.setText("USUARIO:");
        jPanel1.add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        txt_username1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txt_username1.setForeground(new java.awt.Color(204, 204, 204));
        txt_username1.setText("Ingrese su usuario");
        txt_username1.setBorder(null);
        txt_username1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_username1MousePressed(evt);
            }
        });
        txt_username1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_username1ActionPerformed(evt);
            }
        });
        jPanel1.add(txt_username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 340, 40));

        Separeitor_username1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(Separeitor_username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 340, 10));

        passwordUser.setForeground(new java.awt.Color(204, 204, 204));
        passwordUser.setText("**********");
        passwordUser.setBorder(null);
        passwordUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passwordUserMousePressed(evt);
            }
        });
        passwordUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordUserActionPerformed(evt);
            }
        });
        jPanel1.add(passwordUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 340, 40));

        btn_Login.setBackground(new java.awt.Color(207, 0, 162));
        btn_Login.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_Login.setText("INGRESAR");
        btn_Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LoginActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 110, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FONDO MORADO1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FONDO MORADO1.jpg"))); // NOI18N
        jLabel2.setText("jLabel1");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 330, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_username1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_username1MousePressed
       
        if(txt_username1.getText().equals("Ingrese su usuario")){
            txt_username1.setText("");
            txt_username1.setForeground(Color.black);
        }
        if(String.valueOf(passwordUser.getPassword()).isEmpty() ){
            passwordUser.setText("**********");
            passwordUser.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txt_username1MousePressed

    private void passwordUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordUserMousePressed
       
        if(String.valueOf(passwordUser.getPassword()).equals("**********")){
            passwordUser.setText("");
            passwordUser.setForeground(Color.black);
        }
        if(txt_username1.getText().isEmpty() ){
            txt_username1.setText("Ingrese su usuario");
            txt_username1.setForeground(Color.gray);
        }

    }//GEN-LAST:event_passwordUserMousePressed

    private Frm_InterfaceSchedule frmIS;
    private void btn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoginActionPerformed
        login();
    }//GEN-LAST:event_btn_LoginActionPerformed

    
    private Frm_InterfaceHelp frmIA;
    private void btn_helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_helpActionPerformed
        frmIA = new Frm_InterfaceHelp();
        this.setVisible(false);
        frmIA.setVisible(true);
    }//GEN-LAST:event_btn_helpActionPerformed

    private void passwordUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordUserActionPerformed
        btn_Login.requestFocus();
        login();
    }//GEN-LAST:event_passwordUserActionPerformed

    private void txt_username1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_username1ActionPerformed
        btn_Login.requestFocus();
        login();
    }//GEN-LAST:event_txt_username1ActionPerformed

////    /**
////     * @param args the command line arguments
////     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Frm_InterfaceLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Frm_InterfaceLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Frm_InterfaceLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Frm_InterfaceLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Frm_InterfaceLogin().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator Separeitor_password;
    private javax.swing.JSeparator Separeitor_username1;
    private javax.swing.JButton btn_Login;
    private javax.swing.JButton btn_help;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_LeatherFlowerSystem;
    private javax.swing.JLabel lbl_Lguito;
    private javax.swing.JLabel lbl_SoloLogo1;
    private javax.swing.JLabel lbl_SpaFondo1;
    private javax.swing.JLabel lbl_SpaFondo2;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JPasswordField passwordUser;
    private javax.swing.JTextField txt_username1;
    // End of variables declaration//GEN-END:variables
}
