
package ec.edu.espe.Spa.view;

/**
 *
 * @author Steven Pozo, Erick Moreira, Elkin Pabón, Diego Ponce, DCCO-ESPE, DEES Developers
 */
public class Panel_Home extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Home
     */
    public Panel_Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_Logo = new javax.swing.JLabel();
        lbl_Logo3 = new javax.swing.JLabel();
        lbl_Logo2 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(900, 550));
        setPreferredSize(new java.awt.Dimension(900, 550));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("CITAS DENTRO DEL ESTABLECIMIENTO");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, -1, -1));

        jLabel13.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("ESTA APLICACION FUE PROGRAMADA");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, -1, -1));

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setText("Y HECHA EXCLUSIVAMENTE PARA EL");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, -1, -1));

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 102));
        jLabel15.setText("USO DE ESTEFANIA MORETA.");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, -1, -1));

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 102));
        jLabel16.setText("ESTA APP SERÁ DE AYUDA PARA AGENDAR");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SPA.jpeg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 320, 220));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FLOR_DE_PIEL_BN_sin fondo1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 420, 350));

        jLabel11.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        jLabel11.setText("BIENVENIDA ESTEFANIA");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        lbl_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FONDO SPA_paneles.jpg"))); // NOI18N
        lbl_Logo.setText("jLabel11");
        jPanel1.add(lbl_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 347, 550));

        lbl_Logo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FONDO SPA_paneles.jpg"))); // NOI18N
        lbl_Logo3.setText("jLabel11");
        jPanel1.add(lbl_Logo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 347, 550));

        lbl_Logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FONDO SPA_paneles.jpg"))); // NOI18N
        lbl_Logo2.setText("jLabel11");
        jPanel1.add(lbl_Logo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 320, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_Logo;
    private javax.swing.JLabel lbl_Logo2;
    private javax.swing.JLabel lbl_Logo3;
    // End of variables declaration//GEN-END:variables
}
