
package ec.edu.espe.Spa.view;


import com.mongodb.MongoClient;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import static com.mongodb.client.model.Filters.eq;
import com.toedter.calendar.JDateChooser;
import ec.edu.espe.Spa.controller.CustomerController;
import ec.edu.espe.Spa.controller.ServiceController;
import ec.edu.espe.Spa.controller.MongoDBConnection;
import ec.edu.espe.Spa.model.Service;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import org.bson.Document;
import static org.bson.codecs.configuration.CodecRegistries.fromProviders;
import static org.bson.codecs.configuration.CodecRegistries.fromRegistries;
import org.bson.codecs.configuration.CodecRegistry;
import org.bson.codecs.pojo.PojoCodecProvider;



/**
 *
 * @author Steven Pozo, Erick Moreira, Elkin Pabón, Diego Ponce, DCCO-ESPE, DEES Developers
 */
public class Panel_allData extends javax.swing.JPanel {

    /**
     * Creates new form Panel_allData
     */
    public Panel_allData() {
        initComponents();
        MongoDBConnection.connectDatabase();
        loadService();
    }
    
SimpleDateFormat formDate = new SimpleDateFormat("dd-MM-yy");
    
    public String getDate(JDateChooser jdDate){
        if(jdDate.getDate() != null){
            return formDate.format(jdDate.getDate());
        } 
        else{
            return null;
        }
    }
    
    public void loadService(){
        MongoDBConnection.connectDatabase();
        CodecRegistry codecRegistry = fromRegistries(MongoClient.getDefaultCodecRegistry(),fromProviders(PojoCodecProvider.builder().automatic(true).build()));
        MongoDatabase db = MongoDBConnection.connectDatabase().withCodecRegistry(codecRegistry);
        MongoCollection<Service> collectionService = db.getCollection("Services", Service.class); 
        
        List<Service> services = collectionService.find(new Document(), Service.class).into(new ArrayList<Service>());

        for (Service service : services) {
            cmb_Type.addItem(service.getTypeOfService());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbDataCustomer = new javax.swing.JLabel();
        lblSN = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblCEllphone = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblTOS = new javax.swing.JLabel();
        lblCost = new javax.swing.JLabel();
        lblCost1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblFN1 = new javax.swing.JLabel();
        sp_sessions = new javax.swing.JSpinner();
        txt_lastName = new javax.swing.JTextField();
        txt_firstName = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txt_Id = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        txt_Cellphone = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        txt_Email = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        txt_Cost = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        txt_TimeOT = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        cmb_Type = new javax.swing.JComboBox<>();
        jSeparator8 = new javax.swing.JSeparator();
        btn_Register = new javax.swing.JButton();
        btn_Cancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        calendarDate = new com.toedter.calendar.JDateChooser();
        txt_Hour = new javax.swing.JFormattedTextField();
        btn_Invoice = new javax.swing.JButton();
        txt_costTotal = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        btn_calculate = new javax.swing.JButton();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 550));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 550));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbDataCustomer.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbDataCustomer.setText("REGISTRAR CLIENTE");
        jPanel1.add(lbDataCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        lblSN.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSN.setForeground(new java.awt.Color(51, 51, 255));
        lblSN.setText("APELLIDOS:");
        jPanel1.add(lblSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, 30));

        lblId.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblId.setForeground(new java.awt.Color(51, 51, 255));
        lblId.setText("# IDENTIFICACIÓN:");
        jPanel1.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 190, -1));

        lblCEllphone.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblCEllphone.setForeground(new java.awt.Color(51, 51, 255));
        lblCEllphone.setText("TELÉFONO:");
        jPanel1.add(lblCEllphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

        lblEmail.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(51, 51, 255));
        lblEmail.setText("E-MAIL:");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));

        lblTOS.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblTOS.setForeground(new java.awt.Color(51, 51, 255));
        lblTOS.setText("TIPO DE SERVICIO:");
        jPanel1.add(lblTOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, -1, -1));

        lblCost.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblCost.setForeground(new java.awt.Color(51, 51, 255));
        lblCost.setText("COSTO:");
        jPanel1.add(lblCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, -1, -1));

        lblCost1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblCost1.setForeground(new java.awt.Color(51, 51, 255));
        lblCost1.setText("# DE SESIONES");
        jPanel1.add(lblCost1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("TOTAL A PAGAR:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, -1, -1));

        lblFN1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblFN1.setForeground(new java.awt.Color(51, 51, 255));
        lblFN1.setText("NOMBRES:");
        jPanel1.add(lblFN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        sp_sessions.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 10.0d, 1.0d));
        jPanel1.add(sp_sessions, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, -1, 40));

        txt_lastName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_lastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_lastNameKeyTyped(evt);
            }
        });
        jPanel1.add(txt_lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 270, 40));

        txt_firstName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_firstNameActionPerformed(evt);
            }
        });
        txt_firstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_firstNameKeyTyped(evt);
            }
        });
        jPanel1.add(txt_firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 270, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 270, 10));

        txt_Id.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_Id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_IdKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_IdKeyTyped(evt);
            }
        });
        jPanel1.add(txt_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 270, 40));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 270, 10));

        jSeparator11.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 20, 120));

        txt_Cellphone.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_Cellphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_CellphoneKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_CellphoneKeyTyped(evt);
            }
        });
        jPanel1.add(txt_Cellphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 270, 40));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 270, 10));

        txt_Email.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txt_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 270, 40));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 270, 10));

        txt_Cost.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_Cost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CostActionPerformed(evt);
            }
        });
        txt_Cost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_CostKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_CostKeyTyped(evt);
            }
        });
        jPanel1.add(txt_Cost, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 70, 40));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, 70, 10));

        txt_TimeOT.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_TimeOT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TimeOTActionPerformed(evt);
            }
        });
        jPanel1.add(txt_TimeOT, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 260, 40));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 260, 10));

        cmb_Type.setBackground(new java.awt.Color(153, 255, 204));
        cmb_Type.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmb_Type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jPanel1.add(cmb_Type, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 260, 40));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 260, 10));

        btn_Register.setBackground(new java.awt.Color(0, 255, 255));
        btn_Register.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_Register.setText("REGISTRAR");
        btn_Register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Register.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btn_RegisterStateChanged(evt);
            }
        });
        btn_Register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_RegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_RegisterMouseExited(evt);
            }
        });
        btn_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, -1, 30));

        btn_Cancel.setBackground(new java.awt.Color(0, 255, 255));
        btn_Cancel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_Cancel.setText("CANCELAR");
        btn_Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_CancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_CancelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_CancelMousePressed(evt);
            }
        });
        btn_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 420, -1, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("FECHA:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 80, 20));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("HORA DE ATENCIÓN:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, 160, 30));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 120, 10));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 180, 50, 10));
        jPanel1.add(calendarDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 150, 40));

        try {
            txt_Hour.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_Hour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_HourActionPerformed(evt);
            }
        });
        txt_Hour.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_HourKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_HourKeyTyped(evt);
            }
        });
        jPanel1.add(txt_Hour, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, 50, 30));

        btn_Invoice.setBackground(new java.awt.Color(0, 255, 255));
        btn_Invoice.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_Invoice.setText("FACTURA");
        btn_Invoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_InvoiceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_InvoiceMouseExited(evt);
            }
        });
        btn_Invoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InvoiceActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Invoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 420, 120, 30));

        txt_costTotal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_costTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_costTotalActionPerformed(evt);
            }
        });
        txt_costTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_costTotalKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_costTotalKeyTyped(evt);
            }
        });
        jPanel1.add(txt_costTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 70, 40));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 70, 10));

        btn_calculate.setBackground(new java.awt.Color(0, 255, 255));
        btn_calculate.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        btn_calculate.setText("CALCULAR");
        btn_calculate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_calculateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_calculateMouseExited(evt);
            }
        });
        btn_calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calculateActionPerformed(evt);
            }
        });
        jPanel1.add(btn_calculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, -1, 20));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, 50, 10));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("$");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, 20, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("$");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 20, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setText("DURACION:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 240, 10));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/doc_Impresion1.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 420, 30, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FONDO SPA_paneles.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FONDO SPA_paneles.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 330, 550));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FONDO SPA_paneles.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 310, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegisterActionPerformed
    
    CustomerController customerController;
    customerController = new CustomerController("Customers");
        
    MongoCollection<Document> collection = MongoDBConnection.database.getCollection("Customers");
    Document doc = collection.find(eq("identification", txt_Id.getText())).first();
        
    if(doc == null){
        if(txt_Id.getText().length()<10 || txt_Cellphone.getText().length()<10){
            JOptionPane.showConfirmDialog(this,"El número de identificación o teléfono están incompletos \n" + "El número de indetificación y teléfono deben tener 10 números","Aviso",JOptionPane.WARNING_MESSAGE);     
        }else if(txt_firstName.getText().isEmpty() || txt_lastName.getText().isEmpty() || txt_Id.getText().isEmpty() || txt_Cellphone.getText().isEmpty() || txt_Email.getText().isEmpty()  || cmb_Type.getSelectedItem().toString().isEmpty()  ||txt_Cost.getText().isEmpty()  ||txt_TimeOT.getText().isEmpty()  ||formDate.format(calendarDate.getDate()).isEmpty()  ||txt_Hour.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Registro inválido \n" +"Algunos campos de texto están vacios", "Error",JOptionPane.ERROR_MESSAGE);
    }else{
        int i =  JOptionPane.showConfirmDialog(this,"Registrar Cliente?","Aviso",JOptionPane.WARNING_MESSAGE);
        
            if(i==0){
                customerController.createToDatabase(customerController.RegisterAndBuildDocument(txt_firstName.getText(), 
                    txt_lastName.getText(),
                    txt_Id.getText(),
                    txt_Cellphone.getText(),
                    txt_Email.getText(), 
                    cmb_Type.getSelectedItem().toString(), 
                    txt_Cost.getText(), 
                    txt_TimeOT.getText(), 
                    formDate.format(calendarDate.getDate()), 
                    txt_Hour.getText()));
                    JOptionPane.showMessageDialog(this, "Datos guardados exitosamente");
                
                        txt_firstName.setText("");
                        txt_lastName.setText("");
                        txt_Id.setText("");
                        txt_Cellphone.setText("");
                        txt_Email.setText("");
                        txt_Cost.setText("");
                        txt_TimeOT.setText("");
                        txt_Hour.setText("");
                
            }else if(i==1){
                this.setVisible(true);
            }
    }
        } 
        else{
           JOptionPane.showMessageDialog(this, "Ya existe un cliente registrado con el número de identificación\n "+txt_Id.getText()+" Ingrese nuevamente \n"); 
        }
    }//GEN-LAST:event_btn_RegisterActionPerformed

    private void txt_firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_firstNameActionPerformed

    }//GEN-LAST:event_txt_firstNameActionPerformed

    private void txt_firstNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_firstNameKeyTyped
 
    char validateLetters = evt.getKeyChar();
        if(Character.isDigit(validateLetters)){
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese solo letras","Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txt_firstNameKeyTyped

    private void txt_CellphoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CellphoneKeyPressed
  
    }//GEN-LAST:event_txt_CellphoneKeyPressed

    private void txt_IdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_IdKeyPressed

    }//GEN-LAST:event_txt_IdKeyPressed

    private void btn_CancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CancelMouseEntered
        btn_Cancel.setBackground(Color.red);
    }//GEN-LAST:event_btn_CancelMouseEntered

    private void btn_CancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CancelMouseExited
        btn_Cancel.setBackground(Color.cyan);
    }//GEN-LAST:event_btn_CancelMouseExited

    private void btn_RegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_RegisterMouseEntered
        btn_Register.setBackground(Color.green);
    }//GEN-LAST:event_btn_RegisterMouseEntered

    private void btn_RegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_RegisterMouseExited
        btn_Register.setBackground(Color.cyan);
    }//GEN-LAST:event_btn_RegisterMouseExited

    private void btn_CancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CancelMousePressed
        int i =  JOptionPane.showConfirmDialog(this,"Quiere cancelar? Los datos no se han guardado","Error",JOptionPane.WARNING_MESSAGE);
        if(i==0){
        txt_firstName.setText("");
        txt_lastName.setText("");
        txt_Id.setText("");
        txt_Cellphone.setText("");
        txt_Email.setText("");
        txt_Cost.setText("");
        txt_TimeOT.setText("");
        txt_Hour.setText("");
        }else if(i==1){
            this.setVisible(true);
        }
    }//GEN-LAST:event_btn_CancelMousePressed

    private void txt_HourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_HourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_HourActionPerformed

    private void txt_HourKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_HourKeyPressed
        ServiceController hour;
        hour = new ServiceController("Customers");
        if(hour.validateHour(txt_Hour.getText())== false){
         
        }
    }//GEN-LAST:event_txt_HourKeyPressed

    private void txt_HourKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_HourKeyTyped
    
    }//GEN-LAST:event_txt_HourKeyTyped

    private void txt_lastNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_lastNameKeyTyped
        //   validado por Erick Moreira
        char validateLetters = evt.getKeyChar();
        if(Character.isDigit(validateLetters)){
        evt.consume();
        JOptionPane.showMessageDialog(this, "Ingrese solo letras","Aviso",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txt_lastNameKeyTyped

    private void txt_CostKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CostKeyTyped
        char character = evt.getKeyChar();
        
        if(((character < '0' || character > '9')) && (character != KeyEvent.VK_BACK_SPACE)
            && (character != '.' || txt_Cost.getText().contains(".") )){
            evt.consume();
        }
    }//GEN-LAST:event_txt_CostKeyTyped

    private void btn_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelActionPerformed
        //
    }//GEN-LAST:event_btn_CancelActionPerformed

    private void btn_InvoiceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_InvoiceMouseEntered
        btn_Invoice.setBackground(Color.green);
    }//GEN-LAST:event_btn_InvoiceMouseEntered

    private void btn_InvoiceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_InvoiceMouseExited
        btn_Invoice.setBackground(Color.cyan);
    }//GEN-LAST:event_btn_InvoiceMouseExited

    private void btn_InvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InvoiceActionPerformed
  
     //   Panel_Invoice.recibe.setText(txt_firstName.getText());
        Frm_InvoiceCustomer FrmIC;
        FrmIC = new Frm_InvoiceCustomer();
        FrmIC.setVisible(true);

       // Panel_Invoice.recibe.setText(txt_firstName.getText());
        
    }//GEN-LAST:event_btn_InvoiceActionPerformed

    private void txt_IdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_IdKeyTyped
  

        int key = evt.getKeyChar();
        
        boolean onlyNumbers = key >= 48 && key <= 57;
        
        if(!onlyNumbers){
            evt.consume();
        }
        if(txt_Id.getText().length()>=10){
            JOptionPane.showMessageDialog(this, "El número de identificación debe tener 10 números","Aviso",JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_txt_IdKeyTyped

    private void txt_CellphoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CellphoneKeyTyped
        int key = evt.getKeyChar();
        
        boolean onlyNumbers = key >= 48 && key <= 57;
        
        if(!onlyNumbers){
            evt.consume();
        }
        if(txt_Cellphone.getText().length()>=10){
            JOptionPane.showMessageDialog(this, "El número de teléfono debe tener 10 números","Aviso",JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_txt_CellphoneKeyTyped

    private void btn_RegisterStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btn_RegisterStateChanged
        
    }//GEN-LAST:event_btn_RegisterStateChanged

    private void txt_TimeOTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TimeOTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TimeOTActionPerformed

    private void txt_CostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CostActionPerformed

    private void txt_CostKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CostKeyPressed
        
    }//GEN-LAST:event_txt_CostKeyPressed

    private void txt_costTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_costTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_costTotalActionPerformed

    private void txt_costTotalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_costTotalKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_costTotalKeyPressed

    private void txt_costTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_costTotalKeyTyped
        char character = evt.getKeyChar();
        
        if(((character < '0' || character > '9')) && (character != KeyEvent.VK_BACK_SPACE)
            && (character != '.' || txt_costTotal.getText().contains(".") )){
            evt.consume();
        }
        else if(txt_costTotal.getText().length() == 5){
                evt.consume();
            }
    }//GEN-LAST:event_txt_costTotalKeyTyped

    private void btn_calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calculateActionPerformed
//        double cost;
//        double numberSessions;
//        
//        cost = Double.parseDouble(txt_costTotal.getText());
//        numberSessions = Double.parseDouble(sp_sessions.getName());
//        CustomerController CController= new CustomerController("Customers");
//        CController.calculateTotalCost(cost, numberSessions);
//        
//        txt_Cost.setText(String.valueOf(CController.calculateTotalCost(cost, numberSessions)));


    float cost;
    float numberSessions;
            DecimalFormat df = new DecimalFormat("#.00");

            cost = Float.parseFloat(txt_costTotal.getText());
            numberSessions = Float.parseFloat(sp_sessions.getValue().toString());
            float sum = cost * numberSessions;
        
            txt_Cost.setText(""+ df.format(sum));
    }//GEN-LAST:event_btn_calculateActionPerformed

    private void btn_calculateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_calculateMouseEntered
        btn_calculate.setBackground(Color.green);
    }//GEN-LAST:event_btn_calculateMouseEntered

    private void btn_calculateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_calculateMouseExited
        btn_calculate.setBackground(Color.cyan);
    }//GEN-LAST:event_btn_calculateMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancel;
    private javax.swing.JButton btn_Invoice;
    private javax.swing.JButton btn_Register;
    private javax.swing.JButton btn_calculate;
    private com.toedter.calendar.JDateChooser calendarDate;
    public static javax.swing.JComboBox<String> cmb_Type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lbDataCustomer;
    private javax.swing.JLabel lblCEllphone;
    private javax.swing.JLabel lblCost;
    private javax.swing.JLabel lblCost1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFN1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblSN;
    private javax.swing.JLabel lblTOS;
    private javax.swing.JSpinner sp_sessions;
    private javax.swing.JTextField txt_Cellphone;
    private javax.swing.JTextField txt_Cost;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JFormattedTextField txt_Hour;
    public javax.swing.JTextField txt_Id;
    private javax.swing.JTextField txt_TimeOT;
    private javax.swing.JTextField txt_costTotal;
    public static javax.swing.JTextField txt_firstName;
    public javax.swing.JTextField txt_lastName;
    // End of variables declaration//GEN-END:variables
}
