
package ec.edu.espe.Spa.view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Steven Pozo, Erick Moreira, Elkin Pabón, Diego Ponce, DCCO-ESPE, DEES Developers
 */
public class Frm_InterfaceAyuda extends javax.swing.JFrame {

    /**
     * Creates new form Dentrode_interfaz
     */
    public Frm_InterfaceAyuda() {
        
        initComponents();
        this.setTitle("Leather Flower");
        setIconImage(getIconImage());
     //   setIconImage(new ImageIcon(getClass().getResource("/Images/SoloLogo1.png")).getImage());
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Images/logoSinFondo.png"));
        return retValue;
    }

    private void showPanel(JPanel p){
        p.setSize(810,530);
        p.setLocation(0,0);
        
        Contenido.removeAll();
        Contenido.add(p,BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel_about = new javax.swing.JPanel();
        lbl_signopregunta = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panel_Contact = new javax.swing.JPanel();
        lbl_signopregunta1 = new javax.swing.JLabel();
        lbl_Contactt = new javax.swing.JLabel();
        lbl_Logo = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Contenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1210, 620));
        setPreferredSize(new java.awt.Dimension(1210, 620));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 620));
        jPanel1.setPreferredSize(new java.awt.Dimension(1210, 620));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_about.setBackground(new java.awt.Color(0, 255, 255));
        panel_about.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_aboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_aboutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_aboutMousePressed(evt);
            }
        });

        lbl_signopregunta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/inter1.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("ABOUT APPLICATION");

        javax.swing.GroupLayout panel_aboutLayout = new javax.swing.GroupLayout(panel_about);
        panel_about.setLayout(panel_aboutLayout);
        panel_aboutLayout.setHorizontalGroup(
            panel_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_aboutLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(lbl_signopregunta)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_aboutLayout.setVerticalGroup(
            panel_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_aboutLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panel_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_signopregunta)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel1.add(panel_about, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 400, -1));

        panel_Contact.setBackground(new java.awt.Color(0, 255, 255));
        panel_Contact.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_Contact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_ContactMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_ContactMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_ContactMousePressed(evt);
            }
        });

        lbl_signopregunta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/contactos1.png"))); // NOI18N

        lbl_Contactt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_Contactt.setText("CONTACT");

        javax.swing.GroupLayout panel_ContactLayout = new javax.swing.GroupLayout(panel_Contact);
        panel_Contact.setLayout(panel_ContactLayout);
        panel_ContactLayout.setHorizontalGroup(
            panel_ContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ContactLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(lbl_signopregunta1)
                .addGap(18, 18, 18)
                .addComponent(lbl_Contactt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_ContactLayout.setVerticalGroup(
            panel_ContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ContactLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panel_ContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_signopregunta1)
                    .addComponent(lbl_Contactt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(panel_Contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 400, -1));

        lbl_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Lguito.png"))); // NOI18N
        jPanel1.add(lbl_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 400, -1));

        btn_back.setBackground(new java.awt.Color(0, 255, 204));
        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backjava.png"))); // NOI18N
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel1.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 40, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/franja_MA.jpg"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 620, 80));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/franja_MA.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 650, 80));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/franja_MA.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 650, 80));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/franja_MA.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 650, 80));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/franja_MA.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 650, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/franja_MA.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/franja_MA.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 620));

        Contenido.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ContenidoLayout = new javax.swing.GroupLayout(Contenido);
        Contenido.setLayout(ContenidoLayout);
        ContenidoLayout.setHorizontalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        ContenidoLayout.setVerticalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        jPanel1.add(Contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 810, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Frm_InterfaceInicial frmII;
    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        frmII = new Frm_InterfaceInicial();
        this.setVisible(false);
        frmII.setVisible(true);
    }//GEN-LAST:event_btn_backActionPerformed

    private void panel_ContactMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_ContactMousePressed
        Panel_Contact frmContact;
        frmContact = new Panel_Contact();
        showPanel(frmContact);
    }//GEN-LAST:event_panel_ContactMousePressed

    private void panel_ContactMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_ContactMouseExited
        panel_Contact.setBackground(Color.cyan);
    }//GEN-LAST:event_panel_ContactMouseExited

    private void panel_ContactMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_ContactMouseEntered
        panel_Contact.setBackground(Color.white);
    }//GEN-LAST:event_panel_ContactMouseEntered

    private void panel_aboutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_aboutMousePressed
        Panel_InformationDEES frmInfo;
        frmInfo = new Panel_InformationDEES();
        showPanel(frmInfo);
    }//GEN-LAST:event_panel_aboutMousePressed

    private void panel_aboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_aboutMouseExited
        panel_about.setBackground(Color.cyan);
    }//GEN-LAST:event_panel_aboutMouseExited

    private void panel_aboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_aboutMouseEntered
        panel_about.setBackground(Color.white);
    }//GEN-LAST:event_panel_aboutMouseEntered

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Frm_InterfaceAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Frm_InterfaceAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Frm_InterfaceAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Frm_InterfaceAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Frm_InterfaceAyuda().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenido;
    private javax.swing.JButton btn_back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_Contactt;
    private javax.swing.JLabel lbl_Logo;
    private javax.swing.JLabel lbl_signopregunta;
    private javax.swing.JLabel lbl_signopregunta1;
    private javax.swing.JPanel panel_Contact;
    private javax.swing.JPanel panel_about;
    // End of variables declaration//GEN-END:variables
}
