
package ec.edu.espe.Spa.view;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Steven Pozo, Erick Moreira, Elkin Pabón, Diego Ponce, DCCO-ESPE, DEES Developers
 */
public class Frm_InterfaceInicial extends javax.swing.JFrame {

    /**
     * Creates new form intefaz_Inicial
     */
    public Frm_InterfaceInicial() {
        initComponents();
        this.setTitle("Leather Flower");
        setIconImage(getIconImage());
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Images/logoSinFondo.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_Lguito = new javax.swing.JLabel();
        lbl_SpaFondo2 = new javax.swing.JLabel();
        lbl_SpaFondo1 = new javax.swing.JLabel();
        lbl_SoloLogo1 = new javax.swing.JLabel();
        lbl_LeatherFlowerSystem = new javax.swing.JLabel();
        lbl_password = new javax.swing.JLabel();
        Separeitor_password = new javax.swing.JSeparator();
        lbl_username = new javax.swing.JLabel();
        txt_username1 = new javax.swing.JTextField();
        Separeitor_username1 = new javax.swing.JSeparator();
        jPassword = new javax.swing.JPasswordField();
        btn_Login = new javax.swing.JButton();
        Panel_verde = new javax.swing.JPanel();
        Panel_MenuBar = new javax.swing.JPanel();
        btn_help = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1210, 620));
        jPanel1.setPreferredSize(new java.awt.Dimension(1210, 620));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Lguito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LogoSpa.png"))); // NOI18N
        jPanel1.add(lbl_Lguito, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, 400, 220));

        lbl_SpaFondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SpaFondo1.jpg"))); // NOI18N
        lbl_SpaFondo2.setText("jLabel1");
        jPanel1.add(lbl_SpaFondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 350, 620));

        lbl_SpaFondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SpaFondo1.jpg"))); // NOI18N
        lbl_SpaFondo1.setText("jLabel1");
        jPanel1.add(lbl_SpaFondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 350, 620));

        lbl_SoloLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SoloLogo1.png"))); // NOI18N
        jPanel1.add(lbl_SoloLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        lbl_LeatherFlowerSystem.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        lbl_LeatherFlowerSystem.setText("Leather Flower System");
        jPanel1.add(lbl_LeatherFlowerSystem, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 240, -1));

        lbl_password.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_password.setText("PASSWORD:");
        jPanel1.add(lbl_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        Separeitor_password.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(Separeitor_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 407, 340, -1));

        lbl_username.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_username.setText("USERNAME:");
        jPanel1.add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        txt_username1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txt_username1.setForeground(new java.awt.Color(204, 204, 204));
        txt_username1.setText("Enter your username");
        txt_username1.setBorder(null);
        txt_username1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_username1MousePressed(evt);
            }
        });
        jPanel1.add(txt_username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 340, 40));

        Separeitor_username1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(Separeitor_username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 340, 10));

        jPassword.setForeground(new java.awt.Color(204, 204, 204));
        jPassword.setText("************");
        jPassword.setBorder(null);
        jPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPasswordMousePressed(evt);
            }
        });
        jPanel1.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 340, 40));

        btn_Login.setBackground(new java.awt.Color(207, 0, 162));
        btn_Login.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_Login.setText("LOGIN");
        btn_Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LoginActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 100, 40));

        Panel_verde.setBackground(new java.awt.Color(153, 244, 184));

        javax.swing.GroupLayout Panel_verdeLayout = new javax.swing.GroupLayout(Panel_verde);
        Panel_verde.setLayout(Panel_verdeLayout);
        Panel_verdeLayout.setHorizontalGroup(
            Panel_verdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        Panel_verdeLayout.setVerticalGroup(
            Panel_verdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(Panel_verde, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 300, 40));

        Panel_MenuBar.setBackground(new java.awt.Color(153, 255, 204));

        btn_help.setBackground(new java.awt.Color(204, 255, 204));
        btn_help.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_help.setText("Help");
        btn_help.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_helpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_MenuBarLayout = new javax.swing.GroupLayout(Panel_MenuBar);
        Panel_MenuBar.setLayout(Panel_MenuBarLayout);
        Panel_MenuBarLayout.setHorizontalGroup(
            Panel_MenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_MenuBarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btn_help)
                .addContainerGap(486, Short.MAX_VALUE))
        );
        Panel_MenuBarLayout.setVerticalGroup(
            Panel_MenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_MenuBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_help)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel1.add(Panel_MenuBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_username1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_username1MousePressed
       
        if(txt_username1.getText().equals("Enter your username")){
            txt_username1.setText("");
            txt_username1.setForeground(Color.black);
        }
        if(String.valueOf(jPassword.getPassword()).isEmpty() ){
            jPassword.setText("***********");
            jPassword.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txt_username1MousePressed

    private void jPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordMousePressed
       
        if(String.valueOf(jPassword.getPassword()).equals("***********")){
            jPassword.setText("");
            jPassword.setForeground(Color.black);
        }
        if(txt_username1.getText().isEmpty() ){
            txt_username1.setText("Enter your username");
            txt_username1.setForeground(Color.gray);
        }
        
    }//GEN-LAST:event_jPasswordMousePressed

    private Frm_InterfaceSchedule frmIS;
    private void btn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoginActionPerformed
    char clave[]=jPassword.getPassword();
    String clavedef=new String(clave);

    if (txt_username1.getText().equals("ella") && clavedef.equals("ella2")){

            this.dispose();
            frmIS = new Frm_InterfaceSchedule();
            frmIS.setVisible(true);

    }else {
            JOptionPane.showMessageDialog(null, "USER OR PASSWORD INVALID:\n"
            + "Enter the username or password again", "Access denied",
            JOptionPane.ERROR_MESSAGE);
            txt_username1.setText("");
            jPassword.setText("");
    }
    }//GEN-LAST:event_btn_LoginActionPerformed

    
    private Frm_InterfaceAyuda frmIA;
    private void btn_helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_helpActionPerformed
        frmIA = new Frm_InterfaceAyuda();
        this.setVisible(false);
        frmIA.setVisible(true);
    }//GEN-LAST:event_btn_helpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_InterfaceInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_InterfaceInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_InterfaceInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_InterfaceInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_InterfaceInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_MenuBar;
    private javax.swing.JPanel Panel_verde;
    private javax.swing.JSeparator Separeitor_password;
    private javax.swing.JSeparator Separeitor_username1;
    private javax.swing.JButton btn_Login;
    private javax.swing.JButton btn_help;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JLabel lbl_LeatherFlowerSystem;
    private javax.swing.JLabel lbl_Lguito;
    private javax.swing.JLabel lbl_SoloLogo1;
    private javax.swing.JLabel lbl_SpaFondo1;
    private javax.swing.JLabel lbl_SpaFondo2;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JTextField txt_username1;
    // End of variables declaration//GEN-END:variables
}
