
package ec.edu.espe.Spa.view;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;

/**
 *
 * @author Steven Pozo, Erick Moreira, Elkin Pabón, Diego Ponce, DCCO-ESPE, DEES Developers
 */
public class Panel_Invoice extends javax.swing.JPanel implements Printable {

    /**
     * Creates new form Panel_Invoice
     */
    public Panel_Invoice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_date = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        txt_total = new javax.swing.JTextField();
        txt_firstName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_lastName = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_time = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_type = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txt_hour = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jLabel5.setText("FLOWER");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 70, 20));

        jLabel6.setFont(new java.awt.Font("Courier New", 2, 10)); // NOI18N
        jLabel6.setText("0988774933");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel1.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jLabel1.setText("LEATHER");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 80, -1));

        jLabel2.setFont(new java.awt.Font("Courier New", 2, 14)); // NOI18N
        jLabel2.setText("SPA for all");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logoSinFondo.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel7.setFont(new java.awt.Font("Courier New", 1, 10)); // NOI18N
        jLabel7.setText("Contacts:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 70, -1));

        jLabel8.setFont(new java.awt.Font("Courier New", 1, 10)); // NOI18N
        jLabel8.setText("Date:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 40, -1));

        jLabel9.setFont(new java.awt.Font("Courier New", 2, 10)); // NOI18N
        jLabel9.setText("Av.Oswaldo Guayasamín 1/2, Quito 170903 ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel10.setFont(new java.awt.Font("Courier New", 1, 10)); // NOI18N
        jLabel10.setText("SURNAMES");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 70, -1));

        txt_date.setFont(new java.awt.Font("Courier New", 0, 10)); // NOI18N
        txt_date.setForeground(new java.awt.Color(204, 204, 204));
        txt_date.setText("Enter date today");
        txt_date.setBorder(null);
        txt_date.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_dateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_dateMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_dateMousePressed(evt);
            }
        });
        txt_date.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_dateKeyTyped(evt);
            }
        });
        jPanel1.add(txt_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 110, 20));

        jLabel11.setFont(new java.awt.Font("Courier New", 1, 10)); // NOI18N
        jLabel11.setText("City:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 40, -1));

        jLabel12.setFont(new java.awt.Font("Courier New", 2, 10)); // NOI18N
        jLabel12.setText("Quito-Valle de Tumbaco");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel13.setFont(new java.awt.Font("Courier New", 1, 10)); // NOI18N
        jLabel13.setText("Address:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 60, -1));

        jLabel14.setFont(new java.awt.Font("Courier New", 1, 10)); // NOI18N
        jLabel14.setText("DESCRIPTION");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 80, 20));

        jLabel15.setFont(new java.awt.Font("Courier New", 1, 10)); // NOI18N
        jLabel15.setText("CUSTOMER");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 60, -1));

        jLabel16.setFont(new java.awt.Font("Courier New", 1, 10)); // NOI18N
        jLabel16.setText("TOTAL:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, 40, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(204, 204, 204));
        jTextArea1.setRows(5);
        jTextArea1.setText("Enter information or description of\ncustomer or service.");
        jTextArea1.setBorder(null);
        jTextArea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextArea1MousePressed(evt);
            }
        });
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextArea1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 260, 140));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 220, 10));

        txt_total.setFont(new java.awt.Font("Courier New", 0, 10)); // NOI18N
        txt_total.setForeground(new java.awt.Color(204, 204, 204));
        txt_total.setText("Cost");
        txt_total.setBorder(null);
        txt_total.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_totalMousePressed(evt);
            }
        });
        txt_total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_totalKeyTyped(evt);
            }
        });
        jPanel1.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 490, 50, 20));

        txt_firstName.setFont(new java.awt.Font("Courier New", 0, 10)); // NOI18N
        txt_firstName.setForeground(new java.awt.Color(204, 204, 204));
        txt_firstName.setText("Enter Names");
        txt_firstName.setBorder(null);
        txt_firstName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_firstNameMousePressed(evt);
            }
        });
        txt_firstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_firstNameKeyTyped(evt);
            }
        });
        jPanel1.add(txt_firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 120, 20));

        jLabel17.setFont(new java.awt.Font("Courier New", 1, 10)); // NOI18N
        jLabel17.setText("NAMES");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 70, -1));

        txt_lastName.setFont(new java.awt.Font("Courier New", 0, 10)); // NOI18N
        txt_lastName.setForeground(new java.awt.Color(204, 204, 204));
        txt_lastName.setText("Enter Surnames");
        txt_lastName.setBorder(null);
        txt_lastName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_lastNameMousePressed(evt);
            }
        });
        txt_lastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_lastNameKeyTyped(evt);
            }
        });
        jPanel1.add(txt_lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 120, 20));

        jLabel18.setFont(new java.awt.Font("Courier New", 1, 10)); // NOI18N
        jLabel18.setText("TIME OF ATTENTION:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 120, -1));

        txt_time.setFont(new java.awt.Font("Courier New", 0, 10)); // NOI18N
        txt_time.setForeground(new java.awt.Color(204, 204, 204));
        txt_time.setText("Enter time of attention");
        txt_time.setBorder(null);
        txt_time.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_timeMousePressed(evt);
            }
        });
        txt_time.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_timeKeyTyped(evt);
            }
        });
        jPanel1.add(txt_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 190, 20));

        jLabel19.setFont(new java.awt.Font("Courier New", 1, 10)); // NOI18N
        jLabel19.setText("TYPE OF SERVICE:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 120, -1));

        txt_type.setFont(new java.awt.Font("Courier New", 0, 10)); // NOI18N
        txt_type.setForeground(new java.awt.Color(204, 204, 204));
        txt_type.setText("Enter Type Service Selected");
        txt_type.setBorder(null);
        txt_type.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_typeMousePressed(evt);
            }
        });
        txt_type.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_typeKeyTyped(evt);
            }
        });
        jPanel1.add(txt_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 190, 20));

        jLabel20.setFont(new java.awt.Font("Courier New", 1, 10)); // NOI18N
        jLabel20.setText("HOUR AND DATE OF ATTENTION:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 180, -1));

        txt_hour.setFont(new java.awt.Font("Courier New", 0, 10)); // NOI18N
        txt_hour.setForeground(new java.awt.Color(204, 204, 204));
        txt_hour.setText("Enter hour and date");
        txt_hour.setBorder(null);
        txt_hour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_hourMousePressed(evt);
            }
        });
        txt_hour.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_hourKeyTyped(evt);
            }
        });
        jPanel1.add(txt_hour, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 140, 20));

        jLabel21.setText("|");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 520, 10, -1));

        jLabel22.setText("|");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 10, -1));

        jLabel23.setText("|");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 10, -1));

        jLabel24.setText("|");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 10, -1));

        jLabel25.setText("|");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 10, -1));

        jLabel26.setText("|");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 10, -1));

        jLabel27.setText("|");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 10, -1));

        jLabel28.setText("|");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 10, -1));

        jLabel29.setText("|");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 10, -1));

        jLabel30.setText("|");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 10, 20));

        jLabel31.setText("|");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 10, -1));

        jLabel32.setText("|");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 10, -1));

        jLabel33.setText("|");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 10, -1));

        jLabel34.setText("|");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 10, -1));

        jLabel35.setText("|");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 10, -1));

        jLabel36.setText("|");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 10, -1));

        jLabel37.setText("|");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 10, -1));

        jLabel38.setText("|");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 10, -1));

        jLabel39.setText("|");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 10, -1));

        jLabel40.setText("|");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 10, -1));

        jLabel41.setText("|");
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 10, -1));

        jLabel42.setText("|");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, 10, -1));

        jLabel43.setText("|");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, 10, -1));

        jLabel44.setText("|");
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 10, -1));

        jLabel45.setText("|");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 10, -1));

        jLabel46.setText("|");
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 10, -1));

        jLabel47.setText("|");
        jPanel1.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 10, -1));

        jLabel48.setText("|");
        jPanel1.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 10, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 120, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 280, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 120, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 120, 10));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 510, 60, 10));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 220, 10));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 220, 10));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 220, 10));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 220, 10));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 220, 10));

        jLabel4.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel4.setText("$");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, 20, 20));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 100, 10));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 120, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_dateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_dateMouseEntered
       
    }//GEN-LAST:event_txt_dateMouseEntered

    private void txt_dateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_dateMouseExited
        
    }//GEN-LAST:event_txt_dateMouseExited

    private void txt_dateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_dateMousePressed
       txt_date.setText("");
    }//GEN-LAST:event_txt_dateMousePressed

    private void txt_dateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_dateKeyTyped
        txt_date.setForeground(Color.black);
    }//GEN-LAST:event_txt_dateKeyTyped

    private void txt_firstNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_firstNameMousePressed
        txt_firstName.setText("");
    }//GEN-LAST:event_txt_firstNameMousePressed

    private void txt_firstNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_firstNameKeyTyped
        txt_firstName.setForeground(Color.black);
    }//GEN-LAST:event_txt_firstNameKeyTyped

    private void txt_lastNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_lastNameMousePressed
        txt_lastName.setText("");
    }//GEN-LAST:event_txt_lastNameMousePressed

    private void txt_lastNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_lastNameKeyTyped
        txt_lastName.setForeground(Color.black);
    }//GEN-LAST:event_txt_lastNameKeyTyped

    private void txt_timeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_timeMousePressed
        txt_time.setText("");
    }//GEN-LAST:event_txt_timeMousePressed

    private void txt_timeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_timeKeyTyped
        txt_time.setForeground(Color.black);
    }//GEN-LAST:event_txt_timeKeyTyped

    private void txt_typeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_typeKeyTyped
        txt_type.setForeground(Color.black);
    }//GEN-LAST:event_txt_typeKeyTyped

    private void txt_typeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_typeMousePressed
        txt_type.setText("");
    }//GEN-LAST:event_txt_typeMousePressed

    private void txt_hourMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_hourMousePressed
        txt_hour.setText("");
    }//GEN-LAST:event_txt_hourMousePressed

    private void txt_hourKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_hourKeyTyped
       txt_hour.setForeground(Color.black);
    }//GEN-LAST:event_txt_hourKeyTyped

    private void jTextArea1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea1MousePressed
       jTextArea1.setText("");
    }//GEN-LAST:event_jTextArea1MousePressed

    private void jTextArea1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyTyped
        jTextArea1.setForeground(Color.black);
    }//GEN-LAST:event_jTextArea1KeyTyped

    private void txt_totalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_totalMousePressed
        txt_total.setText("");
    }//GEN-LAST:event_txt_totalMousePressed

    private void txt_totalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_totalKeyTyped
        txt_total.setForeground(Color.black);
    }//GEN-LAST:event_txt_totalKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextField txt_firstName;
    private javax.swing.JTextField txt_hour;
    private javax.swing.JTextField txt_lastName;
    private javax.swing.JTextField txt_time;
    private javax.swing.JTextField txt_total;
    private javax.swing.JTextField txt_type;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
        if(pageIndex==0){
            Graphics2D graphics2D = (Graphics2D) graphics;
            graphics2D.translate(pageFormat.getImageableX(),pageFormat.getImageableY());
            printAll(graphics2D);
            return PAGE_EXISTS;
        } else {
            return NO_SUCH_PAGE;
        }
    }
}
