
package ec.edu.espe.Spa.view;


import java.io.IOException;

/**
 *
 * @author Steven Pozo, DCCO-ESPE, DEES Developers
 */
public class Frm_Welcome extends javax.swing.JFrame {

    /**
     * Creates new form Frm_bienvenido
     */
    public Frm_Welcome() {
        initComponents();
        setLocationRelativeTo(null);
        progressBar.setVisible(false);
        
        
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        porcentaje = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        lbl_text = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe Script", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 204));
        jLabel2.setText("Flor de Piel");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 320, 50));

        porcentaje.setFont(new java.awt.Font("Old English Text MT", 1, 12)); // NOI18N
        porcentaje.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(porcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 30, 20));

        progressBar.setBackground(new java.awt.Color(102, 255, 204));
        progressBar.setForeground(new java.awt.Color(204, 51, 255));
        progressBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 255), new java.awt.Color(0, 204, 204), new java.awt.Color(255, 255, 51), new java.awt.Color(204, 0, 0)));
        jPanel1.add(progressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 360, 10));

        lbl_text.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        lbl_text.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lbl_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 160, 20));

        jLabel3.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel3.setText("WELCOME");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/welcomeM.gif"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        
        Frm_Welcome frmWelcome;
        frmWelcome = new Frm_Welcome();
        frmWelcome.setVisible(true);
        try{
           for(int i=0;i<=100;i++){
               Thread.sleep(100);
               frmWelcome.progressBar.setValue(i);
//               frmWelcome.lbl_text.setText("Initializing application...");
               frmWelcome.porcentaje.setText(Integer.toString(i)+"%");
               if(i==1){
                  frmWelcome.lbl_text.setText("INITIALIZING APLICATION"); 
               }
               if(i==60){
                   frmWelcome.lbl_text.setText("      LOADING DATA");
               }
               if(i==100){
                   frmWelcome.setVisible(false);
                   Frm_InterfaceLogin frmLogin;
                   frmLogin = new Frm_InterfaceLogin();
                   frmLogin.setVisible(true);
               }
           }
    }
       catch(Exception e){
           
       }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_text;
    private javax.swing.JLabel porcentaje;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
