
package ec.edu.espe.Spa.view;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;

/**
 *
 * @author Steven Pozo, Erick Moreira, Elkin Pabón, Diego Ponce, DCCO-ESPE, DEES Developers
 */
public class Panel_Invoice extends javax.swing.JPanel implements Printable {

    /**
     * Creates new form Panel_Invoice
     */
    public Panel_Invoice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_date = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        txt_total = new javax.swing.JTextField();
        txt_firstName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel49 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jSeparator21 = new javax.swing.JSeparator();
        jSeparator22 = new javax.swing.JSeparator();
        jSeparator23 = new javax.swing.JSeparator();
        jSeparator24 = new javax.swing.JSeparator();
        jSeparator25 = new javax.swing.JSeparator();
        jSeparator26 = new javax.swing.JSeparator();
        txt_typeOfService = new javax.swing.JTextField();
        txt_lastName = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jLabel5.setText("FLOWER");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 70, 20));

        jLabel6.setFont(new java.awt.Font("Courier New", 2, 10)); // NOI18N
        jLabel6.setText("0988774933");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel1.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jLabel1.setText("LEATHER");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 80, -1));

        jLabel2.setFont(new java.awt.Font("Courier New", 2, 14)); // NOI18N
        jLabel2.setText("SPA for all");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Courier New", 1, 10)); // NOI18N
        jLabel7.setText("Contacts:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 70, -1));

        jLabel8.setFont(new java.awt.Font("Courier New", 1, 10)); // NOI18N
        jLabel8.setText("Date:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 40, -1));

        jLabel9.setFont(new java.awt.Font("Courier New", 2, 10)); // NOI18N
        jLabel9.setText("Av.Oswaldo Guayasamín 1/2, Quito 170903 ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel10.setFont(new java.awt.Font("Courier New", 1, 10)); // NOI18N
        jLabel10.setText("LAST NAME");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 70, -1));

        txt_date.setFont(new java.awt.Font("Courier New", 0, 10)); // NOI18N
        txt_date.setForeground(new java.awt.Color(204, 204, 204));
        txt_date.setText("Enter date today");
        txt_date.setBorder(null);
        txt_date.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_dateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_dateMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_dateMousePressed(evt);
            }
        });
        txt_date.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_dateKeyTyped(evt);
            }
        });
        jPanel1.add(txt_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 110, 20));

        jLabel11.setFont(new java.awt.Font("Courier New", 1, 10)); // NOI18N
        jLabel11.setText("City:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 40, -1));

        jLabel12.setFont(new java.awt.Font("Courier New", 2, 10)); // NOI18N
        jLabel12.setText("Quito-Valle de Tumbaco");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel13.setFont(new java.awt.Font("Courier New", 1, 10)); // NOI18N
        jLabel13.setText("Address:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 60, -1));

        jLabel14.setFont(new java.awt.Font("Courier New", 1, 10)); // NOI18N
        jLabel14.setText("DESCRIPTION");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 80, 20));

        jLabel15.setFont(new java.awt.Font("Courier New", 1, 10)); // NOI18N
        jLabel15.setText("CUSTOMER");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 60, -1));

        jLabel16.setFont(new java.awt.Font("Courier New", 1, 10)); // NOI18N
        jLabel16.setText("TOTAL:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 40, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(204, 204, 204));
        jTextArea1.setRows(5);
        jTextArea1.setText("Enter description");
        jTextArea1.setBorder(null);
        jTextArea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextArea1MousePressed(evt);
            }
        });
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextArea1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 520, 100));

        txt_total.setFont(new java.awt.Font("Courier New", 0, 10)); // NOI18N
        txt_total.setForeground(new java.awt.Color(204, 204, 204));
        txt_total.setText("Cost");
        txt_total.setBorder(null);
        txt_total.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_totalMousePressed(evt);
            }
        });
        txt_total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_totalKeyTyped(evt);
            }
        });
        jPanel1.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 40, 10));

        txt_firstName.setFont(new java.awt.Font("Courier New", 0, 10)); // NOI18N
        txt_firstName.setForeground(new java.awt.Color(204, 204, 204));
        txt_firstName.setText("enter first name");
        txt_firstName.setBorder(null);
        txt_firstName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_firstNameMousePressed(evt);
            }
        });
        txt_firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_firstNameActionPerformed(evt);
            }
        });
        txt_firstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_firstNameKeyTyped(evt);
            }
        });
        jPanel1.add(txt_firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 277, 110, -1));

        jLabel17.setFont(new java.awt.Font("Courier New", 1, 10)); // NOI18N
        jLabel17.setText("FIRST NAME");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 70, -1));

        jLabel19.setFont(new java.awt.Font("Courier New", 1, 10)); // NOI18N
        jLabel19.setText("TYPE OF SERVICE:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 120, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 120, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 240, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 120, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 120, 10));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 220, 10));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 220, 10));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 60, 10));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 520, 10));

        jLabel4.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel4.setText("$");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 10, 10));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 100, 10));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 120, 10));

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LOGOFP_sin fondo.png"))); // NOI18N
        jPanel1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 60));

        jSeparator14.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 10, 130));
        jPanel1.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 240, 10));

        jSeparator17.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 10, 20));

        jSeparator18.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 10, 130));

        jSeparator19.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 10, 130));

        jSeparator20.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 10, 130));
        jPanel1.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 60, 10));
        jPanel1.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 220, 10));
        jPanel1.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 60, 10));

        jSeparator24.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 10, 110));

        jSeparator25.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 10, 20));
        jPanel1.add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 520, 10));

        txt_typeOfService.setFont(new java.awt.Font("Courier New", 0, 10)); // NOI18N
        txt_typeOfService.setForeground(new java.awt.Color(204, 204, 204));
        txt_typeOfService.setText("enter type of service");
        txt_typeOfService.setBorder(null);
        txt_typeOfService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_typeOfServiceMousePressed(evt);
            }
        });
        txt_typeOfService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_typeOfServiceActionPerformed(evt);
            }
        });
        txt_typeOfService.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_typeOfServiceKeyTyped(evt);
            }
        });
        jPanel1.add(txt_typeOfService, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 190, 10));

        txt_lastName.setFont(new java.awt.Font("Courier New", 0, 10)); // NOI18N
        txt_lastName.setForeground(new java.awt.Color(204, 204, 204));
        txt_lastName.setText("enter last name");
        txt_lastName.setBorder(null);
        txt_lastName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_lastNameMousePressed(evt);
            }
        });
        txt_lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lastNameActionPerformed(evt);
            }
        });
        txt_lastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_lastNameKeyTyped(evt);
            }
        });
        jPanel1.add(txt_lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 277, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_dateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_dateMouseEntered
       
    }//GEN-LAST:event_txt_dateMouseEntered

    private void txt_dateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_dateMouseExited
        
    }//GEN-LAST:event_txt_dateMouseExited

    private void txt_dateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_dateMousePressed
       
        if(txt_date.getText().equals("Enter date today")){
            txt_date.setText("");
        }
    }//GEN-LAST:event_txt_dateMousePressed

    private void txt_dateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_dateKeyTyped
        txt_date.setForeground(Color.black);
    }//GEN-LAST:event_txt_dateKeyTyped

    private void txt_firstNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_firstNameMousePressed
        if(txt_firstName.getText().equals("enter first name")){
            txt_firstName.setText("");
        }
    }//GEN-LAST:event_txt_firstNameMousePressed

    private void txt_firstNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_firstNameKeyTyped
        txt_firstName.setForeground(Color.black);
    }//GEN-LAST:event_txt_firstNameKeyTyped

    private void jTextArea1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea1MousePressed
    jTextArea1.setText("");
    }//GEN-LAST:event_jTextArea1MousePressed

    private void jTextArea1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyTyped
        jTextArea1.setForeground(Color.black);
    }//GEN-LAST:event_jTextArea1KeyTyped

    private void txt_totalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_totalMousePressed
        if(txt_total.getText().equals("Cost")){
            txt_total.setText("");
        }
    }//GEN-LAST:event_txt_totalMousePressed

    private void txt_totalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_totalKeyTyped
        txt_total.setForeground(Color.black);
    }//GEN-LAST:event_txt_totalKeyTyped

    private void txt_firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_firstNameActionPerformed

    }//GEN-LAST:event_txt_firstNameActionPerformed

    private void txt_typeOfServiceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_typeOfServiceMousePressed
        if(txt_typeOfService.getText().equals("enter type of service")){
            txt_typeOfService.setText("");
        }
    }//GEN-LAST:event_txt_typeOfServiceMousePressed

    private void txt_typeOfServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_typeOfServiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_typeOfServiceActionPerformed

    private void txt_typeOfServiceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_typeOfServiceKeyTyped
       txt_typeOfService.setForeground(Color.black);
    }//GEN-LAST:event_txt_typeOfServiceKeyTyped

    private void txt_lastNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_lastNameMousePressed
        if(txt_lastName.getText().equals("enter last name")){
        txt_lastName.setText("");
        }
    }//GEN-LAST:event_txt_lastNameMousePressed

    private void txt_lastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lastNameActionPerformed

    private void txt_lastNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_lastNameKeyTyped
       txt_lastName.setForeground(Color.black);
    }//GEN-LAST:event_txt_lastNameKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txt_date;
    public static javax.swing.JTextField txt_firstName;
    public static javax.swing.JTextField txt_lastName;
    private javax.swing.JTextField txt_total;
    public static javax.swing.JTextField txt_typeOfService;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
        if(pageIndex==0){
            Graphics2D graphics2D = (Graphics2D) graphics;
            graphics2D.translate(pageFormat.getImageableX(),pageFormat.getImageableY());
            printAll(graphics2D);
            return PAGE_EXISTS;
        } else {
            return NO_SUCH_PAGE;
        }
    }
}
